### ISSUE TITLE
Dealing with external software

### ISSUE THREAD

**Issue by cristinae** [albarron/LumpSTS#2]
The ixa-pipes do not have a nice API to be integrated within LumpSTS. Internal parameters are initialised through a CLI and set using a private function. There are 2 options: 1) Modify IXA's code, 2) Call the system with an exec command to use the jar directly. I tried to cheat the system "mimicking" a CLI but it didn't work.

**Comment by cristinae** [comment]
Now ixa-pipes are used as an external software, MIDAMIRA is integrated.

**Comment by albarron** [comment]
So, is this enough to consider the issue closed?

**Comment by albarron** [comment]
I guess the best option would be modifying IXA and doing a pull request. Nevertheless, I'm not sure we have time for such an endeavor.

Are you sure we cannot extend the class and initialise the parameters through the constructor?
