### ISSUE TITLE
Mapping several PoS tagsets into the BabelNet tag set

### ISSUE THREAD

**Issue by cristinae** [albarron/LumpSTS#6]
As expected the mapping among tag sets is not straightforward. I'm not sure how to do it for some of the tags. The most important ones have a comment //think on the code:

 LumpSTS/src/main/java/cat/lump/sts2017/babelNet/PoSMaps.java 

On the other hand, we only keep a subset, so some of the conversions will never be used. This is why some of the fields go to null.

**Comment by albarron** [comment]
I think most cases make sense. A few comments:

AR
- about digit, after looking at [the Wikipedia article](https://en.wikipedia.org/wiki/Determiner), I would go for determiner.
- about latin, the best would be "foreign word", but I guess noun is the best available alternative. 

EN
- I would use DETERMINER for CDF
- I guess it is safe to set null for EX. Still, I'd go for a  verb (linked to things like "is") if necessary.
- I think RP could be an adverb; [see](http://www.ling.upenn.edu/histcorpora/annotation/pos-misc.htm#adverbial_particles)
- TO could be a preposition; [see](https://www.ego4u.com/en/cram-up/grammar/prepositions) 

ES
- About w, I think it could be a noun. 
- The closest thing to a z0 is an adverb as well.

Having said so, we can leave the Spanish tags as they are. 

I basically arrived in the same websites when googling about some of the tags as the ones you comment at the end of the class. Therefore, I would like to move such comments from the end to the specification of each constant.

**Comment by cristinae** [comment]
I've modified some of the options. A couple of comments:

- numbers are still a noun instead of a determiner so that they are considered as a PoS to annotate
- EX is null for the same reason modal verbs are excluded to retrieve IDs. 

By the way, the description of the constants for Arabic is in the MadaMira manual

**Comment by albarron** [comment]
I guess with numbers you mean something we want to take into consideration. That's fine.

Fine with EX
