### ISSUE TITLE
Subset of PoS selected for the BabelNet system

### ISSUE THREAD

**Issue by cristinae** [albarron/LumpSTS#7]
Now, I have selected
- Nouns (including NEs and foreign words)
- Adjectives
- Adverbs
- Verbs

Anything else? Please, check at
 LumpSTS/src/main/java/cat/lump/sts2017/babelNet/PoSAccept.java

**Comment by albarron** [comment]
This is reasonable. I think it is more than safe to leave it as it is. 

Still if you really want to go further, according to my comments on issue #6 ...
Regarding EN:
- Maybe we should add EX (as it would become a verb?)
- Same for RP (as it would become an adverb) 

Regarding ES:
- Are there Babelnet entries for (some) dates? If so, maybe we want to catch them.

I re-arranged POS_AR_ACC and added comments as in the other languages. Please pull.

**Comment by cristinae** [comment]
EX is null for the same reason modal verbs are excluded to retrieve IDs. Should be consider them?

As you say dates are only available for ES. Since we aim at an interlingua corpus of IDs I think we should avoid particular tags of a language.

**Comment by albarron** [comment]
I agree with EX and dates.
